name: modern_vpn_project
description: "New vpn app"


publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.11.11
  cupertino_icons: ^1.0.2
  riverpod: ^2.4.9
  timezone: ^0.9.2
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  grpc: ^3.2.3
  protobuf: ^3.0.0
  basic_utils: ^5.7.0
  asn1lib: ^1.5.0
  file_picker: ^6.1.1
  auto_route: ^7.8.4
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  rxdart: ^0.27.7
  get: ^4.6.6
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/base_app_icon.png"


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/rive/
    - assets/images/
    - assets/images/flags/
