name: modern_vpn_project
description: "New vpn app"


publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.11.11
  cupertino_icons: ^1.0.2
#  riverpod: ^2.4.9
  timezone: ^0.9.2
  path: ^1.8.3
  path_provider: ^2.1.1
  grpc: ^3.2.3
  protobuf: ^3.0.0
  basic_utils: ^5.7.0
  asn1lib: ^1.5.0
  file_picker: ^6.1.1
  auto_route: ^7.8.4
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  rxdart: ^0.27.7
  get: ^4.6.6
  realm: ^1.6.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
#  hive: ^2.2.3
  rx_shared_preferences: ^3.1.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/base_app_icon.png"


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/rive/
    - assets/images/
    - assets/images/flags/
flutter_intl:
  enabled: true
